### ISSUE TITLE
Incompatibility with API <= 22

### ISSUE THREAD

**Issue by jackpeters667** [Tunous/Dawn#310] opened 2020-08-29 01:10 UTC
Hi there. The app crashes on launch on my device. Output is:

`
08/29 03:07:13: Launching 'app' on Nexus 4 API 22.
$ adb shell am start -n "me.thanel.dank.debug/me.saket.dank.Launcher" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 5158 on device 'Nexus_4_API_22 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
E/libprocessgroup: failed to make and chown /acct/uid_10061: Read-only file system
W/Zygote: createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
I/art: Not late-enabling -Xcheck:jni (already on)
W/ResourcesManager: Asset path '/system/framework/android.test.runner.jar' does not exist or contains no resources.
I/stetho: Listening on @stetho_me.thanel.dank.debug_devtools_remote
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/art: Background sticky concurrent mark sweep GC freed 455(89KB) AllocSpace objects, 0(0B) LOS objects, 11% free, 3MB/4MB, paused 22.399ms total 106.262ms
I/art: Rejecting re-init on previously-failed class java.lang.Class<me.saket.dank.utils.-$$Lambda$CombineLatestWithLog$DebugProfiler$C903_0ULWF9FWJ0_xRIIGD0rLpo>
I/art: Rejecting re-init on previously-failed class java.lang.Class<me.saket.dank.utils.-$$Lambda$CombineLatestWithLog$DebugProfiler$C903_0ULWF9FWJ0_xRIIGD0rLpo>
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
    Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.thanel.dank.debug, PID: 5158
    java.lang.RuntimeException: Unable to start activity ComponentInfo{me.thanel.dank.debug/me.saket.dank.ui.subreddit.SubredditActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class me.saket.dank.widgets.InboxUI.InboxRecyclerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class me.saket.dank.widgets.InboxUI.InboxRecyclerView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:220)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421)
        at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at me.saket.dank.ui.preferences.TypefaceInflationInterceptor.intercept(TypefaceInflationInterceptor.java:31)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:399)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at me.saket.dank.ui.subreddit.SubredditActivity.onCreate(SubredditActivity.java:182)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:220) 
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19) 
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421) 
        at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14) 
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30) 
        at me.saket.dank.ui.preferences.TypefaceInflationInterceptor.intercept(TypefaceInflationInterceptor.java:31) 
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30) 
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36) 
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:399) 
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at me.saket.dank.ui.subreddit.SubredditActivity.onCreate(SubredditActivity.java:182) 
        at android.app.Activity.performCreate(Activity.java:5990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: android.content.res.Resources$NotFoundException: File res/color/text_color_secondary.xml from color state list resource ID #0x7f0601c8
        at android.content.res.Resources.loadColorStateList(Resources.java:2592)
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:427)
    	at android.graphics.drawable.GradientDrawable.updateStateFromTypedArray(GradientDrawable.java:10
W/UserAuthListener: session: Optional.empty
`

How can I get past this?

**Comment by AbsurdlySuspicious** [comment] 2020-08-30 16:46
> Nexus_4_API_22 [emulator-5554]

It reproduces on both emulator and real device? If yes, what's your real device model and OS version?

**Comment by jackpeters667** [comment] 2020-09-02 19:02
@AbsurdlySuspicious I just tested with a real device. S7 Edge with API 26. Its working fine

**Comment by AbsurdlySuspicious** [comment] 2020-09-05 14:28
I've tested several apis in emulator:

- api 22 - crashes
- api 23 - comments recyclerview is invisible

Seems like we need to correct minSdk :D

Haven't tested anything >23 tough

**Comment by Tunous** [comment] 2020-09-06 12:45
Here are few problems that I've found when tested on API 22:

App crashes on launch due to overridden `textColorPrimary` and `textColorSecondary` attributes which specify `alpha` value that was introduced in API 23 (https://developer.android.com/reference/android/content/res/ColorStateList#item-attributes). Normally this wouldn't be a problem and the alpha value would be simply ignored, but here the use of an attribute (`?android:disabledAlpha`) instead of number value for the alpha causes the crash. Potential solution would be to simply change that to a number or add alternative resource for lower API versions.

The issue with non loading comments is caused by use of `CombineLatestWithLog.DebugProfiler` marked as targeting API N+, most likely bacause it uses `forEach` on items map not available earlier. Here solution would be to change how this map is iterated and remove the target api attribute.

But, and this is where I've stuck, another issue is that popup menus in preferences (for example for image style) do not show up on this API version. As of now I have no idea what causes this and how to resolve this issue without rewriting that popup menu.

So based on that I'm considering upgrading minimum required API version to 23. Unless someone has idea how to resolve the mentioned issue with popup menu... (assuming that there are no other issues of which I'm not sure)

**Comment by saket** [comment] 2020-09-07 00:56
+1 for minSdkVersion=23

**Closed** 2020-09-08 21:09 UTC
Labels: ❓ help wanted, 🐛 bug
