### ISSUE TITLE
Fix position of option buttons in media viewer

### ISSUE THREAD

**Issue by jonahhw** [Tunous/Dawn#457] opened 2021-06-07 14:59 UTC
**Describe the bug**
The buttons that come up when viewing an image move up each time the menu is closed and reopened
<details>
<summary><b>Screenshots</b></summary>
<br/>
<img src="https://user-images.githubusercontent.com/26726798/121035047-84550000-c77b-11eb-884d-6647d3173bff.png" width="50%" />
<img src="https://user-images.githubusercontent.com/26726798/121035057-85862d00-c77b-11eb-959c-2f77a7ebe172.png" width="50%" />
<img src="https://user-images.githubusercontent.com/26726798/121035153-9b93ed80-c77b-11eb-9b48-a54d47437e28.png" width="50%" />
<img src="https://user-images.githubusercontent.com/26726798/121035073-874ff080-c77b-11eb-98ca-f65dc5dd0d69.png" width="50%" />
<img src="https://user-images.githubusercontent.com/26726798/121035077-88811d80-c77b-11eb-803b-830f8f140f0d.png" width="50%" />
</details>

Between each screenshot, I tapped a few times to close and reopen the menu. Eventually, the buttons end up off the screen.

**To Reproduce**
1. Go to any image
2. Tap on the screen to make the buttons go away, then tap again to make them come back. Repeat to make the effect even more dramatic.

**Expected behavior**
The buttons come back in the same position as when they disappeared

**Smartphone**
 - Device: Google Pixel (first gen)
 - OS: Android 10, LineageOS 17.1 (20210529-NIGHTLY-sailfish)
 - Version 0.12.2 (from f-droid)

**Additional Information**
I think it may be related to #12, but I wasn't sure so I figured it was best to make a new issue

**Comment by msfjarvis** [comment] 2021-06-07 15:24
This appears to be a duplicate of #135

**Comment by jonahhw** [comment] 2021-06-08 19:02
It is indeed. Should I close the issue?

**Comment by msfjarvis** [comment] 2021-06-08 19:29
I'll do it.

**Closed by msfjarvis** 2021-06-08 19:29 UTC
Labels: 🐛 bug
