### ISSUE TITLE
Audio doesnt download

### ISSUE THREAD

**Issue by Igivegoodadvice** [Tunous/Dawn#413] opened 2021-03-17 21:40 UTC
Hey, i just wanna start by saying that this is a great app but truely the only issue that I am currently having with it is that the downloaded videos don't have sound. I have a samsung S9+ with the app version 0.12.2 from FDroid. Please let me know what else I can do to help fix this problem.
Thanks!

**Comment by msfjarvis** [comment] 2021-03-17 23:31
Duplicate of #309

**Closed by msfjarvis** 2021-03-17 23:31 UTC
