### ISSUE TITLE
Typing comment lag

### ISSUE THREAD

**Issue by PootisPaw** [Tunous/Dawn#92] opened 2019-10-20 09:54 UTC
There is a weird lag when typing a comment. I cannot really explain much, so there is a video below showcasing the problem. 
https://gfycat.com/spanishfoolhardyafricanwildcat

**Comment by krux3r** [comment] 2019-10-20 10:01
I can approve that. Been experiencing that from the beggining.

My device is Huawei P10 Lite, rooted 8.0.

**Comment by Esselans** [comment] 2019-10-20 10:06
Seems to be the live markdown. See #9

**Comment by Tunous** [comment] 2019-10-20 12:14
Marking as duplicate of #9

**Closed by Tunous** 2019-10-20 12:14 UTC
Labels: 🐛 bug
