### ISSUE TITLE
A Bottom Navigation Bar that has Sections like : Front Page, Profile, Subreddits, Sorting options and etc. Sorting option is welcome on the top bar as well

### ISSUE THREAD

**Issue by SlySin** [Tunous/Dawn#480] opened 2021-07-06 17:15 UTC

**Comment by AbsurdlySuspicious** [comment] 2021-07-07 07:44
duplicate of #234

**Closed by AbsurdlySuspicious** 2021-07-07 07:44 UTC
Labels: design, duplicate

**Comment by AbsurdlySuspicious** [comment] 2021-07-07 07:49
> duplicate of #234

If you have some ideas on how it could look, please participate there
