### ISSUE TITLE
Currently there seems to be 2 top bars. This bar can be submerged into 1 bar which would allow more space on the front page

### ISSUE THREAD

**Issue by SlySin** [Tunous/Dawn#481] opened 2021-07-06 17:18 UTC

**Comment by AbsurdlySuspicious** [comment] 2021-07-07 07:43
duplicate of #208

**Closed by AbsurdlySuspicious** 2021-07-07 07:43 UTC

**Comment by AbsurdlySuspicious** [comment] 2021-07-07 07:49
> duplicate of #208

There's some discussion on this matter so again if you have any ideas please post them there
