### ISSUE TITLE
Download location

### ISSUE THREAD

**Issue by JZsam** [Tunous/Dawn#449] opened 2021-05-25 11:54 UTC
**Is your feature request related to a problem? Please describe.**
I am looking for wallpapers on some subs and I want to download it a specific folder on my phone.

**Describe the solution you'd like**
In the settings add a place where you can have a button to ask everytime or set a place it will automtical in the folder you want

**Comment by AbsurdlySuspicious** [comment] 2021-05-25 13:15
Duplicate of #250

**Closed by AbsurdlySuspicious** 2021-05-25 13:15 UTC
Labels: 🎁 feature
